package status

const STATUS_ORDER_DISPATCH_TO_FULFILMENT_CENTER = "DISPATCH_TO_FULFILMENT_CENTER"
const STATUS_ORDER_DISPATCH_TO_DRIVER = "DISPATCH_TO_FULFILMENT_DRIVER"

var ALLOWED_STATUS_DISPATCH = map[string]bool{
	STATUS_ORDER_DISPATCH_TO_FULFILMENT_CENTER: true,
	STATUS_ORDER_DISPATCH_TO_DRIVER:            true,
}
