package error

const ERROR_CODE_NOT_HAVE_RESULT = 3000
const ERROR_CODE_TOKEN_SESSION = 4004
const ERROR_CODE_SESSION_EXPIRE = 4005
const ERROR_CODE_USER_NOT_REGISTER_ON_COMPANY = 4006
const ERROR_CODE_COMPANY_NOT_HAVE_ACCESS = 4007
const ERROR_CODE_INVALID_PARAMETER = 4008
const ERROR_CODE_ACCOUNT_NOT_HAVE_ACCESS = 4009

var ERROR_CODE_INTERNAL_SERVER = 5000
